!if 0
Copyright (c) Microsoft Corporation.  All rights reserved.
!endif
!if 0
The use and distribution terms for this software are covered by the
Microsoft Public License (Ms-PL)
http://www.microsoft.com/resources/sharedsource/licensingbasics/publiclicense.mspx
which can be found in the file Ms-PL.txt at the root of this distribution.
By using this software in any fashion, you are agreeing to be bound by
the terms of this license.
            
You must not remove this notice, or any other, from this software.
!endif

!INCLUDE $(_MAKEENVROOT)\makefile.def
