// All rights reserved ADENEO EMBEDDED 2010
/*
================================================================================
*             Texas Instruments OMAP(TM) Platform Software
.
*
* Use of this software is controlled by the terms and conditions found
* in the license agreement under which this software has been supplied.
*
================================================================================
*/
//
//  File:  devicemap.c
//
//  Configuration file for the device list
//
#include "omap3530.h"

const DEVICE_ADDRESS_MAP s_DeviceAddressMap[] = {
//  DeviceAddress    Device id
//------------------------------------------------------------------------------

    {        OMAP_GPIO1_REGS_PA,               OMAP_DEVICE_GPIO1       },
    {        OMAP_GPIO2_REGS_PA,               OMAP_DEVICE_GPIO2       },
    {        OMAP_GPIO3_REGS_PA,               OMAP_DEVICE_GPIO3       },
    {        OMAP_GPIO4_REGS_PA,               OMAP_DEVICE_GPIO4       },
    {        OMAP_GPIO5_REGS_PA,               OMAP_DEVICE_GPIO5       },
    {        OMAP_GPIO6_REGS_PA,               OMAP_DEVICE_GPIO6       },
    {        OMAP_GPTIMER12_REGS_PA,           OMAP_DEVICE_GPTIMER12   },
    {        OMAP_GPTIMER2_REGS_PA,            OMAP_DEVICE_GPTIMER2    },
    {        OMAP_GPTIMER3_REGS_PA,            OMAP_DEVICE_GPTIMER3    },
    {        OMAP_GPTIMER4_REGS_PA,            OMAP_DEVICE_GPTIMER4    },
    {        OMAP_GPTIMER5_REGS_PA,            OMAP_DEVICE_GPTIMER5    },
    {        OMAP_GPTIMER6_REGS_PA,            OMAP_DEVICE_GPTIMER6    },
    {        OMAP_GPTIMER7_REGS_PA,            OMAP_DEVICE_GPTIMER7    },
    {        OMAP_GPTIMER8_REGS_PA,            OMAP_DEVICE_GPTIMER8    },
    {        OMAP_GPTIMER9_REGS_PA,            OMAP_DEVICE_GPTIMER9    },
    {        OMAP_GPTIMER10_REGS_PA,           OMAP_DEVICE_GPTIMER10   },
    {        OMAP_GPTIMER11_REGS_PA,           OMAP_DEVICE_GPTIMER11   },
    {        OMAP_MCBSP1_REGS_PA,              OMAP_DEVICE_MCBSP1      },
    {        OMAP_MCBSP2_REGS_PA,              OMAP_DEVICE_MCBSP2      },
    {        OMAP_MCBSP3_REGS_PA,              OMAP_DEVICE_MCBSP3      },
    {        OMAP_MCBSP4_REGS_PA,              OMAP_DEVICE_MCBSP4      },
    {        OMAP_MCBSP5_REGS_PA,              OMAP_DEVICE_MCBSP5      },
    {        OMAP_UART1_REGS_PA,               OMAP_DEVICE_UART1       },
    {        OMAP_UART2_REGS_PA,               OMAP_DEVICE_UART2       },
    {        OMAP_I2C1_REGS_PA,                OMAP_DEVICE_I2C1        },
    {        OMAP_I2C2_REGS_PA,                OMAP_DEVICE_I2C2        },
    {        OMAP_I2C3_REGS_PA,                OMAP_DEVICE_I2C3        },
    {        OMAP_MCSPI1_REGS_PA,              OMAP_DEVICE_MCSPI1      },
    {        OMAP_MCSPI2_REGS_PA,              OMAP_DEVICE_MCSPI2      },
    {        OMAP_MCSPI3_REGS_PA,              OMAP_DEVICE_MCSPI3      },
    {        OMAP_MCSPI4_REGS_PA,              OMAP_DEVICE_MCSPI4      },
    {        OMAP_MMCHS1_REGS_PA,              OMAP_DEVICE_MMC1        },
    {        OMAP_MMCHS2_REGS_PA,              OMAP_DEVICE_MMC2        },
    {        OMAP_MMCHS3_REGS_PA,              OMAP_DEVICE_MMC3        },
    {        OMAP_HSUSB_REGS_PA,               OMAP_DEVICE_HSOTGUSB    },
    {        OMAP_GPTIMER1_REGS_PA,            OMAP_DEVICE_GPTIMER1    },
    {        OMAP_UART3_REGS_PA,               OMAP_DEVICE_UART3       },
    {        OMAP_HDQ_1WIRE_REGS_PA,           OMAP_DEVICE_HDQ         },
    {        OMAP_SGX_REGS_PA,                 OMAP_DEVICE_SGX         },
    {        OMAP_SSI_REGS_PA,                 OMAP_DEVICE_SSI         },
    {        OMAP_SDRC_REGS_PA,                OMAP_DEVICE_SDRC        },
    {        OMAP_WDOG1_REGS_PA,               OMAP_DEVICE_WDT1        },
    {        OMAP_WDOG2_REGS_PA,               OMAP_DEVICE_WDT2        },
    {        OMAP_WDOG3_REGS_PA,               OMAP_DEVICE_WDT3        },
    {        OMAP_32KSYNC_REGS_PA,             OMAP_DEVICE_32KSYNC     },
    {        OMAP_CONFIG_REGS_PA,              OMAP_DEVICE_OMAPCTRL    },
    {        OMAP_DSS1_REGS_PA,                OMAP_DEVICE_DSS         },
    {        OMAP_CAMISP_REGS_PA,              OMAP_DEVICE_CAMERA      },
    {        OMAP_MLB1_REGS_PA,                OMAP_DEVICE_MAILBOXES   },
    {        OMAP_USBUHH_REGS_PA,	           OMAP_DEVICE_USBHOST1    },
    {        OMAP_USBUHH_REGS_PA,			   OMAP_DEVICE_USBHOST2    },
    {        OMAP_USBUHH_REGS_PA,			   OMAP_DEVICE_USBHOST3    },
    {        OMAP_USBTLL_REGS_PA,              OMAP_DEVICE_USBTLL      },
    {        OMAP_CAMCSI2_RECEIVER_REGS_PA,    OMAP_DEVICE_CSI2        },
    {        OMAP_USIM_REG_PA,                 OMAP_DEVICE_USIM        },
    {        OMAP_VRFB_REGS_PA,                OMAP_DEVICE_VRFB        },
    {        OMAP3530_GENERIC,                 OMAP_DEVICE_GENERIC     },
    {        OMAP_VENC1_REGS_PA,               OMAP_DEVICE_TVOUT       }, 
    {        OMAP_SMARTREFLEX1_PA,             OMAP_DEVICE_SR1         },
    {        OMAP_SMARTREFLEX2_PA,             OMAP_DEVICE_SR2         },
    {        OMAP_PRCM_IVA2_CM_REGS_PA,        OMAP_DEVICE_DSP         },
    {        OMAP_UART4_REGS_PA,        OMAP_DEVICE_UART4         },
#if 0
    {        OMAP_2D_REGS_PA,                  OMAP_DEVICE_2D          },
    {        OMAP_3D_REGS_PA,                  OMAP_DEVICE_3D          },
    {        OMAP_MSPRO_REGS_PA,               OMAP_DEVICE_MSPRO       },
    {        OMAP_DES2_REGS_PA,                OMAP_DEVICE_DES2        },
    {        OMAP_SHA12_REGS_PA,               OMAP_DEVICE_SHA12       },
    {        OMAP_AES2_REGS_PA,                OMAP_DEVICE_AES2        },
    {        OMAP_ICR_REGS_PA,                 OMAP_DEVICE_ICR         },
    {        OMAP_DES1_REGS_PA,                OMAP_DEVICE_DES1        },
    {        OMAP_SHA11_REGS_PA,               OMAP_DEVICE_SHA11       },
    {        OMAP_RNG_REGS_PA,                 OMAP_DEVICE_RNG         },
    {        OMAP_AES1_REGS_PA,                OMAP_DEVICE_AES1        },
    {        OMAP_PKA_REGS_PA,                 OMAP_DEVICE_PKA         },
    {        OMAP_D2D_REGS_PA,                 OMAP_DEVICE_D2D         },
#endif
    {        OMAP_SDMA_REGS_PA,                OMAP_DEVICE_SDMA        },
    {        0,                                OMAP_DEVICE_NONE        }
};


const DEVICE_IRQ_MAP s_DeviceIrqMap[]=
{
    // IRQ              Device              Extra
    {4              ,OMAP_DEVICE_MCBSP2     ,L"overflow"    },
    {5              ,OMAP_DEVICE_MCBSP3     ,L"overflow"    },
    {12             ,OMAP_DEVICE_SDMA       ,L"IRQ0"        },
    {13             ,OMAP_DEVICE_SDMA       ,L"IRQ1"        },
    {14             ,OMAP_DEVICE_SDMA       ,L"IRQ2"        },
    {15             ,OMAP_DEVICE_SDMA       ,L"IRQ3"        },
    {16             ,OMAP_DEVICE_MCBSP1     ,NULL           },
    {17             ,OMAP_DEVICE_MCBSP2     ,NULL           },
    {18             ,OMAP_DEVICE_SR1        ,NULL           },
    {19             ,OMAP_DEVICE_SR2        ,NULL           },
    {20             ,OMAP_DEVICE_GPMC       ,NULL           },
    {21             ,OMAP_DEVICE_SGX        ,NULL           },
    {22             ,OMAP_DEVICE_MCBSP3     ,NULL           },
    {23             ,OMAP_DEVICE_MCBSP4     ,NULL           },
    {24             ,OMAP_DEVICE_CAMERA     ,NULL           },       
    {25             ,OMAP_DEVICE_DSS        ,NULL           },
    {26             ,OMAP_DEVICE_MAILBOXES  ,NULL           },
    {27             ,OMAP_DEVICE_MCBSP5     ,NULL           },
    {28             ,OMAP_DEVICE_DSP        ,L"MMU"         },
    {29             ,OMAP_DEVICE_GPIO1      ,NULL           },
    {30             ,OMAP_DEVICE_GPIO2      ,NULL           },
    {31             ,OMAP_DEVICE_GPIO3      ,NULL           },
    {32             ,OMAP_DEVICE_GPIO4      ,NULL           },
    {33             ,OMAP_DEVICE_GPIO5      ,NULL           },
    {34             ,OMAP_DEVICE_GPIO6      ,NULL           },
    {36             ,OMAP_DEVICE_WDT3       ,NULL           },
    {37             ,OMAP_DEVICE_GPTIMER1   ,NULL           },
    {38             ,OMAP_DEVICE_GPTIMER2   ,NULL           },
    {39             ,OMAP_DEVICE_GPTIMER3   ,NULL           },
    {40             ,OMAP_DEVICE_GPTIMER4   ,NULL           },
    {41             ,OMAP_DEVICE_GPTIMER5   ,NULL           },
    {42             ,OMAP_DEVICE_GPTIMER6   ,NULL           },
    {43             ,OMAP_DEVICE_GPTIMER7   ,NULL           },
    {44             ,OMAP_DEVICE_GPTIMER8   ,NULL           },
    {45             ,OMAP_DEVICE_GPTIMER9   ,NULL           },
    {46             ,OMAP_DEVICE_GPTIMER10  ,NULL           },
    {47             ,OMAP_DEVICE_GPTIMER11  ,NULL           },
    {48             ,OMAP_DEVICE_MCSPI4     ,NULL           }, 
    {54             ,OMAP_DEVICE_MCBSP4     ,L"TX"          },
    {55             ,OMAP_DEVICE_MCBSP4     ,L"RX"          },
    {56             ,OMAP_DEVICE_I2C1       ,NULL           },
    {57             ,OMAP_DEVICE_I2C2       ,NULL           },
    {58             ,OMAP_DEVICE_HDQ        ,NULL           },
    {59             ,OMAP_DEVICE_MCBSP1     ,L"TX"          },
    {60             ,OMAP_DEVICE_MCBSP1     ,L"RX"          },
    {61             ,OMAP_DEVICE_I2C3       ,NULL           },
    {62             ,OMAP_DEVICE_MCBSP2     ,L"TX"          },
    {63             ,OMAP_DEVICE_MCBSP2     ,L"RX"          },
    {65             ,OMAP_DEVICE_MCSPI1     ,NULL           },
    {66             ,OMAP_DEVICE_MCSPI2     ,NULL           },
	{71				,OMAP_DEVICE_HSOTGUSB	,NULL			},    
    {72             ,OMAP_DEVICE_UART1      ,NULL           },
    {73             ,OMAP_DEVICE_UART2      ,NULL           },
    {74             ,OMAP_DEVICE_UART3      ,NULL           },
    {76				,OMAP_DEVICE_HSUSB1		,NULL			},
	{77				,OMAP_DEVICE_HSUSB2		,NULL			},
	{78				,OMAP_DEVICE_USBTLL		,NULL			},
    {80             ,OMAP_DEVICE_UART4      ,NULL           },   	
    {81             ,OMAP_DEVICE_MCBSP5     ,L"TX"          },
    {82             ,OMAP_DEVICE_MCBSP5     ,L"RX"          },
    {83             ,OMAP_DEVICE_MMC1       ,NULL           },
    {86             ,OMAP_DEVICE_MMC2       ,NULL           },
    {89             ,OMAP_DEVICE_MCBSP3     ,L"TX"          },
    {90             ,OMAP_DEVICE_MCBSP3     ,L"RX"          },
    {91             ,OMAP_DEVICE_MCSPI3     ,NULL           },
    {94             ,OMAP_DEVICE_MMC3       ,NULL           },
    {0              ,OMAP_DEVICE_NONE       ,NULL           }
};
