// All rights reserved ADENEO EMBEDDED 2010
//
// Copyright (c) MPC Data Limited 2009.  All rights reserved.
//
//------------------------------------------------------------------------------
//
//  File:  am3517_usb.h
//
//  AM3517 USB Peripheral Register Definitions.
//  

#ifndef __AM3517_USB_H__
#define __AM3517_USB_H__

#define AM3517_USB0_REGS_PA			  OMAP_USBHS_REGS_PA
#define AM3517_CPPI_REGS_PA			  OMAP_USBHS_REGS_PA + 0x1000
#define IRQ_USB0_INT				  (71)

// Generic bit mask defines
#ifndef BIT0
  #define BIT0    (0x00000001)
  #define BIT1    (0x00000002)
  #define BIT2    (0x00000004)
  #define BIT3    (0x00000008)
  #define BIT4    (0x00000010)
  #define BIT5    (0x00000020)
  #define BIT6    (0x00000040)
  #define BIT7    (0x00000080)
  #define BIT8    (0x00000100)
  #define BIT9    (0x00000200)
  #define BIT10   (0x00000400)
  #define BIT11   (0x00000800)
  #define BIT12   (0x00001000)
  #define BIT13   (0x00002000)
  #define BIT14   (0x00004000)
  #define BIT15   (0x00008000)
  #define BIT16   (0x00010000)
  #define BIT17   (0x00020000)
  #define BIT18   (0x00040000)
  #define BIT19   (0x00080000)
  #define BIT20   (0x00100000)
  #define BIT21   (0x00200000)
  #define BIT22   (0x00400000)
  #define BIT23   (0x00800000)
  #define BIT24   (0x01000000)
  #define BIT25   (0x02000000)
  #define BIT26   (0x04000000)
  #define BIT27   (0x08000000)
  #define BIT28   (0x10000000)
  #define BIT29   (0x20000000)
  #define BIT30   (0x40000000)
  #define BIT31   (0x80000000)
#endif
  
//------------------------------------------------------------------------------

/*
 * HDRC-specific definitions
 */

#define MGC_MAX_USB_ENDS          16
#define MGC_END0_FIFOSIZE         64   /* this is non-configurable */
#define MGC_FIFO_RAM_SIZE         32768

#define USB_CPPI_MAX_TX_CHANNELS  15
#define USB_CPPI_MAX_RX_CHANNELS  15
#define USB_CPPI_MAX_CHANNELS     (USB_CPPI_MAX_RX_CHANNELS + USB_CPPI_MAX_TX_CHANNELS)
#define USB_CPPI_MAX_QUEUES       96
#define USB_CPPI_MAX_MEMREGIONS   16

/* Interrupts */
#define USB_OTG_TXINT_MASK        0x0000FFFF
#define USB_OTG_RXINT_MASK        0xFFFE0000
#define USB_OTG_USBINT_MASK       0x01ff0000
#define USB_OTG_TXINT_SHIFT       0
#define USB_OTG_RXINT_SHIFT       16
#define USB_OTG_USBINT_SHIFT      16

/* Teardown register shifts */
#define USB_OTG_RXTD_SHIFT       0
#define USB_OTG_TXTD_SHIFT       16

/**************************************************************************\
* Register Overlay Structure for EPTRG 
\**************************************************************************/
typedef struct  {
    volatile UINT8 TXFUNCADDR;
    volatile UINT8 RSVD_0x01;
    volatile UINT8 TXHUBADDR;
    volatile UINT8 TXHUBPORT;
    volatile UINT8 RXFUNCADDR;
    volatile UINT8 RSVD_0x05;
    volatile UINT8 RXHUBADDR;
    volatile UINT8 RXHUBPORT;
} CSL_UsbEptrgRegs;

/**************************************************************************\
* Register Overlay Structure for EPCSR 
\**************************************************************************/
typedef struct  {
    volatile UINT16 TXMAXP;
    volatile UINT16 TXCSR;
    volatile UINT16 RXMAXP;
    volatile UINT16 RXCSR;
    volatile UINT16 RXCOUNT;
    volatile UINT8  TXTYPE;
    volatile UINT8  TXINTERVAL;
    volatile UINT8  RXTYPE;
    volatile UINT8  RXINTERVAL;
    volatile UINT8  RSVD_0x0e;
    volatile UINT8  RSVD_0x0f;
} CSL_UsbEpcsrRegs;

/**************************************************************************\
* Register Overlay Structure for CDMA Channel 
\**************************************************************************/
typedef struct  {
    volatile UINT32 TXGCR;
    volatile UINT32 RSVD_0x04;
    volatile UINT32 RXGCR;
    volatile UINT32 HPCRA;
    volatile UINT32 HPCRB;
    volatile UINT32 RSVD_0x14_0x1c[3];
} CSL_ChannelRegs;

/**************************************************************************\
* Register Overlay Structure for Queue Manager Memory Region
\**************************************************************************/
typedef struct  {
    volatile UINT32 QMEMRBASE;
    volatile UINT32 QMEMRCTRL;
    volatile UINT32 RSVD_0x08_0x0c[2];
} CSL_QueueMgrMemoryRegionRegs;

/**************************************************************************\
* Register Overlay Structure for Queue Management
\**************************************************************************/
typedef struct {
    volatile UINT32 RSVD_0x00;
    volatile UINT32 RSVD_0x04;
    volatile UINT32 RSVD_0x08;
    volatile UINT32 QCTRLD;
} CSL_QueueMgmtRegs;

#define QMGR_QUEUE_N_REG_C_PKTSZ_SHIFT     0
#define QMGR_QUEUE_N_REG_C_PKTSZ_MASK      (0x00003fff << QMGR_QUEUE_N_REG_C_PKTSZ_SHIFT)

#define QMGR_QUEUE_N_REG_D_DESCSZ_SHIFT    0
#define QMGR_QUEUE_N_REG_D_DESCSZ_MASK     (0x0000001f << QMGR_QUEUE_N_REG_D_DESCSZ_SHIFT)
#define QMGR_QUEUE_N_REG_D_DESC_ADDR_SHIFT 5
#define QMGR_QUEUE_N_REG_D_DESC_ADDR_MASK  (0x07ffffff << QMGR_QUEUE_N_REG_D_DESC_ADDR_SHIFT)

/**************************************************************************\
* Register Overlay Structure for Queue Status
\**************************************************************************/
typedef struct {
    volatile UINT32 QSTATA;
    volatile UINT32 QSTATB;
    volatile UINT32 QSTATC;
    volatile UINT32 RSVD_0x000c;
} CSL_QueueStatusRegs;

/**************************************************************************\
* Register Overlay Structure for USB controller
\**************************************************************************/
typedef struct  {
    volatile UINT32 REVID;
    volatile UINT32 CTRLR;
    volatile UINT32 STATR;
    volatile UINT32 EMUR;
    volatile UINT32	RSVD_0x010_0x014;			// volatile UINT32 MODE;
    volatile UINT32 AUTOREQR;
    volatile UINT32 SRPFIXTIME;
    volatile UINT32 TEARDOWN;
    volatile UINT32 EP_INTSRCR;
    volatile UINT32 EP_INTSETR;
    volatile UINT32 EP_INTCLRR;
    volatile UINT32 EP_INTMSKR;
    volatile UINT32 EP_INTMSKSETR;
    volatile UINT32 EP_INTMSKCLRR;
    volatile UINT32 EP_INTMASKEDR;	
    volatile UINT32	RSVD_0x03C_0x040;	
    volatile UINT32 CORE_INTSRCR; 			/* 0x040 */
	volatile UINT32 CORE_INTSETR;
    volatile UINT32 CORE_INTCLRR;
    volatile UINT32 CORE_INTMSKR;
    volatile UINT32 CORE_INTMSKSETR;
    volatile UINT32 CORE_INTMSKCLRR;
    volatile UINT32 CORE_INTMASKEDR;		/* 0x058 */
    volatile UINT32 RSVD_0x05C_0x060;
	volatile UINT32 EOIR;					/* 0x060 */
	volatile UINT32 MOPSOPINTEN;
	volatile UINT32 RSVD_0x064_0x70[2];
	volatile UINT32 TXMODE;					/* 0x070 */
	volatile UINT32 RXMODE;
	volatile UINT32 EP_CNTMODE;
    volatile UINT32 RSVD_0x07C_0x080;
    volatile UINT32 GENRNDISSZ1;			/* 0x080 */
    volatile UINT32 GENRNDISSZ2; 
    volatile UINT32 GENRNDISSZ3; 
    volatile UINT32 GENRNDISSZ4;
    volatile UINT32 GENRNDISSZ5; 
    volatile UINT32 GENRNDISSZ6;
    volatile UINT32 GENRNDISSZ7;
    volatile UINT32 GENRNDISSZ8;
    volatile UINT32 GENRNDISSZ9;
    volatile UINT32 GENRNDISSZ10;
    volatile UINT32 GENRNDISSZ11;
    volatile UINT32 GENRNDISSZ12;
    volatile UINT32 GENRNDISSZ13;
    volatile UINT32 GENRNDISSZ14;
    volatile UINT32 GENRNDISSZ15;			/* 0x0B8 */
    volatile UINT32 RSVD_0x0BC_0x3fc[209];

    /* 0x400 - Common USB registers */
    volatile UINT8  FADDR;
    volatile UINT8  POWER;
    volatile UINT16 INTRTX;
    volatile UINT16 INTRRX;
    volatile UINT16 INTRTXE;
    volatile UINT16 INTRRXE;
    volatile UINT8  INTRUSB;
    volatile UINT8  INTRUSBE;
    volatile UINT16 FRAME;
    volatile UINT8  INDEX;
    volatile UINT8  TESTMODE;

    /* 0x410 - Indexed registers */
    volatile UINT16 TXMAXP;
    volatile UINT16 TXCSR;
    volatile UINT16 RXMAXP;
    volatile UINT16 RXCSR;
    volatile UINT16 RXCOUNT;
    volatile UINT8  TXTYPE;
    volatile UINT8  TXINTERVAL;
    volatile UINT8  RXTYPE;
    volatile UINT8  RXINTERVAL;
    volatile UINT8  RSVD_0x041e;
    volatile UINT8  CONFIGDATA;

    /* 0x420 - FIFOs*/
    volatile UINT32 FIFO[MGC_MAX_USB_ENDS];

    /* 0x460 - Additional Control & Configuration Registers */
    volatile UINT8  DEVCTL;
    volatile UINT8  RSVD_0x0461;
    volatile UINT8  TXFIFOSZ;
    volatile UINT8  RXFIFOSZ;
    volatile UINT16 TXFIFOADDR;
    volatile UINT16 RXFIFOADDR;
    volatile UINT32 RSVD_0x0468;
    volatile UINT16 HWVERS;
    volatile UINT8  RSVD_0x046e_0x047f[18];

    /* 0x480 - Target Endpoint Control Registers (Ep0 - Ep15) */
    CSL_UsbEptrgRegs EPTRG[MGC_MAX_USB_ENDS];
    //volatile UINT8 RSVD_0x04a8_0x04ff[80];

    /* 0x500 - Control and Status Registers (Ep0 - Ep15) */
    CSL_UsbEpcsrRegs EPCSR[MGC_MAX_USB_ENDS];

    /* 0x54e - 0x800 Unused */
    volatile UINT16 RSVD_0x054e;
    volatile UINT32 RSVD_0x0550_0x07fc[127];

	/* 0x800 - OTG Registers */
	volatile UINT32 OTG_Rev;        //  OTG Revision
    volatile UINT32 OTG_SYSCONFIG;  //  System Configuration
    volatile UINT32 OTG_SYSSTATUS;  //  System Status
    volatile UINT32 OTG_INTERFSEL;  //  Interface selection
    volatile UINT32 OTG_SIMENABLE;  //  Simulation Enable
    volatile UINT32 OTG_FORCESTDBY; //  Force Standby
} CSL_UsbRegs;


/**************************************************************************\
* Register Overlay Structure for the CPPI
\**************************************************************************/

typedef struct  {
    /* 0x0000 - CDMA Controller */

    /* 0x0000 - Global Control Registers Region */
    volatile UINT32 DMAREVID;
    volatile UINT32 TDFDQ;
    volatile UINT32 DMAEMU;
    volatile UINT32 RSVD_0x000c_0x07fc[509];

    /* 0x0800 - CDMA Channels */
    CSL_ChannelRegs CDMACHANNEL[USB_CPPI_MAX_CHANNELS];
    volatile UINT32 RSVD_0x0bc0_0x0ffc[272];

    /* 0x1000 - CDMA Scheduler */
    volatile UINT32 DMA_SCHED_CTRL;
    volatile UINT32 RSVD_0x1004_0x17fc[511];

    /* 0x1800 - CDMA Scheduler Table */
    volatile UINT32 CDMASTWORD[64];
    volatile UINT32 RSVD_0x1900_0x2ffc[1472];

    /* 0x3000 - Queue Manager */
    volatile UINT32 QMGRREVID;
    volatile UINT32 RSVD_0x3004;
    volatile UINT32 DIVERSION;
    volatile UINT32 RSVD_0x300c_0x301c[5];
    volatile UINT32 FDBSC[8];
    volatile UINT32 RSVD_0x3030_0x307c[16];
    volatile UINT32 LRAM0BASE;
    volatile UINT32 LRAM0SIZE;
    volatile UINT32 LRAM1BASE;
    volatile UINT32 RSVD_0x308c;
    volatile UINT32 PEND0;
    volatile UINT32 PEND1;
    volatile UINT32 PEND2;
    volatile UINT32 RSVD_0x309c_0x3ffc[985];

    /* 0x4000 - Memory Region Setup */
    CSL_QueueMgrMemoryRegionRegs QMMEMREGION[USB_CPPI_MAX_MEMREGIONS];
    volatile UINT32 RSVD_0x4100_0x4ffc[960];

    /* 0x5000 - Queue Management */
    CSL_QueueMgmtRegs QMQUEUEMGMT[USB_CPPI_MAX_QUEUES];
    volatile UINT32 RSVD_0x5600_0x57fc[128];

    /* 0x5800 - Queue Status */
    CSL_QueueStatusRegs QMQUEUESTATUS[USB_CPPI_MAX_QUEUES];

} CSL_CppiRegs;


/**************************************************************************\
* Overlay structure typedef definition
\**************************************************************************/
typedef volatile CSL_UsbRegs             * CSL_UsbRegsOvly;

#define PERI_TXCSR TXCSR
#define HOST_TXCSR TXCSR
#define PERI_RXCSR RXCSR
#define HOST_RXCSR RXCSR

/**************************************************************************\
* Field Definition Macros
\**************************************************************************/

/* REVR */

#define CSL_USB_REVR_MODID_MASK          (0x3FFF0000u)
#define CSL_USB_REVR_MODID_SHIFT         (0x00000010u)
#define CSL_USB_REVR_MODID_RESETVAL      (0x00000014u)

#define CSL_USB_REVR_REVRTL_MASK         (0x0000F800u)
#define CSL_USB_REVR_REVRTL_SHIFT        (0x0000000Bu)
#define CSL_USB_REVR_REVRTL_RESETVAL     (0x00000000u)

#define CSL_USB_REVR_REVMAJ_MASK         (0x00000700u)
#define CSL_USB_REVR_REVMAJ_SHIFT        (0x00000008u)
#define CSL_USB_REVR_REVMAJ_RESETVAL     (0x00000001u)

#define CSL_USB_REVR_REVMIN_MASK         (0x000000FFu)
#define CSL_USB_REVR_REVMIN_SHIFT        (0x00000000u)
#define CSL_USB_REVR_REVMIN_RESETVAL     (0x00000000u)

#define CSL_USB_REVR_RESETVAL            (0x00140100u)

/* CTRLR */

#define CSL_USB_CTRLR_RNDIS_MASK         (0x00000010u)
#define CSL_USB_CTRLR_RNDIS_SHIFT        (0x00000004u)
#define CSL_USB_CTRLR_RNDIS_RESETVAL     (0x00000000u)

#define CSL_USB_CTRLR_UINT_MASK          (0x00000008u)
#define CSL_USB_CTRLR_UINT_SHIFT         (0x00000003u)
#define CSL_USB_CTRLR_UINT_RESETVAL      (0x00000000u)

#define CSL_USB_CTRLR_CLKFACK_MASK       (0x00000002u)
#define CSL_USB_CTRLR_CLKFACK_SHIFT      (0x00000001u)
#define CSL_USB_CTRLR_CLKFACK_RESETVAL   (0x00000000u)

#define CSL_USB_CTRLR_RESET_MASK         (0x00000001u)
#define CSL_USB_CTRLR_RESET_SHIFT        (0x00000000u)
#define CSL_USB_CTRLR_RESET_RESETVAL     (0x00000000u)

#define CSL_USB_CTRLR_RESETVAL           (0x00000000u)

/* STATR */

#define CSL_USB_STATR_DRVVBUS_MASK       (0x00000001u)
#define CSL_USB_STATR_DRVVBUS_SHIFT      (0x00000000u)
#define CSL_USB_STATR_DRVVBUS_RESETVAL   (0x00000000u)

#define CSL_USB_STATR_RESETVAL           (0x00000000u)

/* EMUR */

#define CSL_USB_EMUR_RTSEL_MASK          (0x00000004u)
#define CSL_USB_EMUR_RTSEL_SHIFT         (0x00000002u)
#define CSL_USB_EMUR_RTSEL_RESETVAL      (0x00000000u)

#define CSL_USB_EMUR_SOFT_MASK           (0x00000002u)
#define CSL_USB_EMUR_SOFT_SHIFT          (0x00000001u)
#define CSL_USB_EMUR_SOFT_RESETVAL       (0x00000001u)

#define CSL_USB_EMUR_FREERUN_MASK        (0x00000001u)
#define CSL_USB_EMUR_FREERUN_SHIFT       (0x00000000u)
#define CSL_USB_EMUR_FREERUN_RESETVAL    (0x00000001u)

#define CSL_USB_EMUR_RESETVAL            (0x00000003u)

/* AUTOREQ */

#define CSL_USB_AUTOREQ_RX4_AUTOREQ_MASK (0x000000C0u)
#define CSL_USB_AUTOREQ_RX4_AUTOREQ_SHIFT (0x00000006u)
#define CSL_USB_AUTOREQ_RX4_AUTOREQ_RESETVAL (0x00000000u)

#define CSL_USB_AUTOREQ_RX3_AUTOREQ_MASK (0x00000030u)
#define CSL_USB_AUTOREQ_RX3_AUTOREQ_SHIFT (0x00000004u)
#define CSL_USB_AUTOREQ_RX3_AUTOREQ_RESETVAL (0x00000000u)

#define CSL_USB_AUTOREQ_RX2_AUTOREQ_MASK (0x0000000Cu)
#define CSL_USB_AUTOREQ_RX2_AUTOREQ_SHIFT (0x00000002u)
#define CSL_USB_AUTOREQ_RX2_AUTOREQ_RESETVAL (0x00000000u)

#define CSL_USB_AUTOREQ_RX1_AUTOREQ_MASK (0x00000003u)
#define CSL_USB_AUTOREQ_RX1_AUTOREQ_SHIFT (0x00000000u)
#define CSL_USB_AUTOREQ_RX1_AUTOREQ_RESETVAL (0x00000000u)

#define CSL_USB_AUTOREQ_RESETVAL         (0x00000000u)

/* INTSRCR */

#define CSL_USB_INTSRCR_USB_MASK         (USB_OTG_USBINT_MASK)
#define CSL_USB_INTSRCR_USB_SHIFT        (USB_OTG_USBINT_SHIFT)
#define CSL_USB_INTSRCR_USB_RESETVAL     (0x00000000u)

#define CSL_USB_INTSRCR_RX_MASK          (USB_OTG_RXINT_MASK)
#define CSL_USB_INTSRCR_RX_SHIFT         (USB_OTG_RXINT_SHIFT)
#define CSL_USB_INTSRCR_RX_RESETVAL      (0x00000000u)

#define CSL_USB_INTSRCR_TX_MASK          (USB_OTG_TXINT_MASK)
#define CSL_USB_INTSRCR_TX_SHIFT         (USB_OTG_TXINT_SHIFT)
#define CSL_USB_INTSRCR_TX_RESETVAL      (0x00000000u)

#define CSL_USB_INTSRCR_RESETVAL         (0x00000000u)

/* INTSETR */

#define CSL_USB_INTSETR_USB_MASK         (USB_OTG_USBINT_MASK)
#define CSL_USB_INTSETR_USB_SHIFT        (USB_OTG_USBINT_SHIFT)
#define CSL_USB_INTSETR_USB_RESETVAL     (0x00000000u)

#define CSL_USB_INTSETR_RX_MASK          (USB_OTG_RXINT_MASK)
#define CSL_USB_INTSETR_RX_SHIFT         (USB_OTG_RXINT_SHIFT)
#define CSL_USB_INTSETR_RX_RESETVAL      (0x00000000u)

#define CSL_USB_INTSETR_TX_MASK          (USB_OTG_TXINT_MASK)
#define CSL_USB_INTSETR_TX_SHIFT         (USB_OTG_TXINT_SHIFT)
#define CSL_USB_INTSETR_TX_RESETVAL      (0x00000000u)

#define CSL_USB_INTSETR_RESETVAL         (0x00000000u)

/* INTCLRR */

#define CSL_USB_INTCLRR_USB_MASK         (USB_OTG_USBINT_MASK)
#define CSL_USB_INTCLRR_USB_SHIFT        (USB_OTG_USBINT_SHIFT)
#define CSL_USB_INTCLRR_USB_RESETVAL     (0x00000000u)

#define CSL_USB_INTCLRR_RX_MASK          (USB_OTG_RXINT_MASK)
#define CSL_USB_INTCLRR_RX_SHIFT         (USB_OTG_RXINT_SHIFT)
#define CSL_USB_INTCLRR_RX_RESETVAL      (0x00000000u)

#define CSL_USB_INTCLRR_TX_MASK          (USB_OTG_TXINT_MASK)
#define CSL_USB_INTCLRR_TX_SHIFT         (USB_OTG_TXINT_SHIFT)
#define CSL_USB_INTCLRR_TX_RESETVAL      (0x00000000u)

#define CSL_USB_INTCLRR_RESETVAL         (0x00000000u)

/* INTMSKR */

#define CSL_USB_INTMSKR_USB_MASK         (USB_OTG_USBINT_MASK)
#define CSL_USB_INTMSKR_USB_SHIFT        (USB_OTG_USBINT_SHIFT)
#define CSL_USB_INTMSKR_USB_RESETVAL     (0x00000000u)

#define CSL_USB_INTMSKR_RX_MASK          (USB_OTG_RXINT_MASK)
#define CSL_USB_INTMSKR_RX_SHIFT         (USB_OTG_RXINT_SHIFT)
#define CSL_USB_INTMSKR_RX_RESETVAL      (0x00000000u)

#define CSL_USB_INTMSKR_TX_MASK          (USB_OTG_TXINT_MASK)
#define CSL_USB_INTMSKR_TX_SHIFT         (USB_OTG_TXINT_SHIFT)
#define CSL_USB_INTMSKR_TX_RESETVAL      (0x00000000u)

#define CSL_USB_INTMSKR_RESETVAL         (0x00000000u)

/* INTMSKSETR */

#define CSL_USB_INTMSKSETR_USB_MASK      (USB_OTG_USBINT_MASK)
#define CSL_USB_INTMSKSETR_USB_SHIFT     (USB_OTG_USBINT_SHIFT)
#define CSL_USB_INTMSKSETR_USB_RESETVAL  (0x00000000u)

#define CSL_USB_INTMSKSETR_RX_MASK       (USB_OTG_RXINT_MASK)
#define CSL_USB_INTMSKSETR_RX_SHIFT      (USB_OTG_RXINT_SHIFT)
#define CSL_USB_INTMSKSETR_RX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMSKSETR_TX_MASK       (USB_OTG_TXINT_MASK)
#define CSL_USB_INTMSKSETR_TX_SHIFT      (USB_OTG_TXINT_SHIFT)
#define CSL_USB_INTMSKSETR_TX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMSKSETR_RESETVAL      (0x00000000u)

/* INTMSKCLRR */

#define CSL_USB_INTMSKCLRR_USB_MASK      (USB_OTG_USBINT_MASK)
#define CSL_USB_INTMSKCLRR_USB_SHIFT     (USB_OTG_USBINT_SHIFT)
#define CSL_USB_INTMSKCLRR_USB_RESETVAL  (0x00000000u)

#define CSL_USB_INTMSKCLRR_RX_MASK       (USB_OTG_RXINT_MASK)
#define CSL_USB_INTMSKCLRR_RX_SHIFT      (USB_OTG_RXINT_SHIFT)
#define CSL_USB_INTMSKCLRR_RX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMSKCLRR_TX_MASK       (USB_OTG_TXINT_MASK)
#define CSL_USB_INTMSKCLRR_TX_SHIFT      (USB_OTG_TXINT_SHIFT)
#define CSL_USB_INTMSKCLRR_TX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMSKCLRR_RESETVAL      (0x00000000u)

/* INTMASKEDR */

#define CSL_USB_INTMASKEDR_USB_MASK      (USB_OTG_USBINT_MASK)
#define CSL_USB_INTMASKEDR_USB_SHIFT     (USB_OTG_USBINT_SHIFT)
#define CSL_USB_INTMASKEDR_USB_RESETVAL  (0x00000000u)

#define CSL_USB_INTMASKEDR_RX_MASK       (USB_OTG_RXINT_MASK)
#define CSL_USB_INTMASKEDR_RX_SHIFT      (USB_OTG_RXINT_SHIFT)
#define CSL_USB_INTMASKEDR_RX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMASKEDR_TX_MASK       (USB_OTG_TXINT_MASK)
#define CSL_USB_INTMASKEDR_TX_SHIFT      (USB_OTG_TXINT_SHIFT)
#define CSL_USB_INTMASKEDR_TX_RESETVAL   (0x00000000u)

#define CSL_USB_INTMASKEDR_RESETVAL      (0x00000000u)

/* EOIR */

#define CSL_USB_EOIR_VECTOR_MASK         (0x000000FFu)
#define CSL_USB_EOIR_VECTOR_SHIFT        (0x00000000u)
#define CSL_USB_EOIR_VECTOR_RESETVAL     (0x00000000u)

#define CSL_USB_EOIR_RESETVAL            (0x00000000u)

/* INTVECTR */

#define CSL_USB_INTVECTR_VECTOR_MASK     (0xFFFFFFFFu)
#define CSL_USB_INTVECTR_VECTOR_SHIFT    (0x00000000u)
#define CSL_USB_INTVECTR_VECTOR_RESETVAL (0x00000000u)

#define CSL_USB_INTVECTR_RESETVAL        (0x00000000u)

/* FADDR */

#define CSL_USB_FADDR_FUNCADDR_MASK      (0x7Fu)
#define CSL_USB_FADDR_FUNCADDR_SHIFT     (0x00u)
#define CSL_USB_FADDR_FUNCADDR_RESETVAL  (0x00u)

#define CSL_USB_FADDR_RESETVAL           (0x00u)

/* POWER */

#define CSL_USB_POWER_ISOUPDATE_MASK     (0x80u)
#define CSL_USB_POWER_ISOUPDATE_SHIFT    (0x07u)
#define CSL_USB_POWER_ISOUPDATE_RESETVAL (0x00u)

#define CSL_USB_POWER_SOFTCONN_MASK      (0x40u)
#define CSL_USB_POWER_SOFTCONN_SHIFT     (0x06u)
#define CSL_USB_POWER_SOFTCONN_RESETVAL  (0x00u)

#define CSL_USB_POWER_HSEN_MASK          (0x20u)
#define CSL_USB_POWER_HSEN_SHIFT         (0x05u)
#define CSL_USB_POWER_HSEN_RESETVAL      (0x01u)

#define CSL_USB_POWER_HSMODE_MASK        (0x10u)
#define CSL_USB_POWER_HSMODE_SHIFT       (0x04u)
#define CSL_USB_POWER_HSMODE_RESETVAL    (0x00u)

#define CSL_USB_POWER_RESET_MASK         (0x08u)
#define CSL_USB_POWER_RESET_SHIFT        (0x03u)
#define CSL_USB_POWER_RESET_RESETVAL     (0x00u)

#define CSL_USB_POWER_RESUME_MASK        (0x04u)
#define CSL_USB_POWER_RESUME_SHIFT       (0x02u)
#define CSL_USB_POWER_RESUME_RESETVAL    (0x00u)

#define CSL_USB_POWER_SUSPENDM_MASK      (0x02u)
#define CSL_USB_POWER_SUSPENDM_SHIFT     (0x01u)
#define CSL_USB_POWER_SUSPENDM_RESETVAL  (0x00u)

#define CSL_USB_POWER_ENSUSPM_MASK       (0x01u)
#define CSL_USB_POWER_ENSUSPM_SHIFT      (0x00u)
#define CSL_USB_POWER_ENSUSPM_RESETVAL   (0x00u)

#define CSL_USB_POWER_RESETVAL           (0x20u)

/* INTRUSB */

#define CSL_USB_INTRUSB_DRVVBUSCHG_MASK     (0x100u)
#define CSL_USB_INTRUSB_DRVVBUSCHG_SHIFT    (0x008u)
#define CSL_USB_INTRUSB_DRVVBUSCHG_RESETVAL (0x000u)

#define CSL_USB_INTRUSB_VBUSERR_MASK     (0x80u)
#define CSL_USB_INTRUSB_VBUSERR_SHIFT    (0x07u)
#define CSL_USB_INTRUSB_VBUSERR_RESETVAL (0x00u)

#define CSL_USB_INTRUSB_SESSREQ_MASK     (0x40u)
#define CSL_USB_INTRUSB_SESSREQ_SHIFT    (0x06u)
#define CSL_USB_INTRUSB_SESSREQ_RESETVAL (0x00u)

#define CSL_USB_INTRUSB_DISCON_MASK      (0x20u)
#define CSL_USB_INTRUSB_DISCON_SHIFT     (0x05u)
#define CSL_USB_INTRUSB_DISCON_RESETVAL  (0x00u)

#define CSL_USB_INTRUSB_CONN_MASK        (0x10u)
#define CSL_USB_INTRUSB_CONN_SHIFT       (0x04u)
#define CSL_USB_INTRUSB_CONN_RESETVAL    (0x00u)

#define CSL_USB_INTRUSB_SOF_MASK         (0x08u)
#define CSL_USB_INTRUSB_SOF_SHIFT        (0x03u)
#define CSL_USB_INTRUSB_SOF_RESETVAL     (0x00u)

#define CSL_USB_INTRUSB_RESET_BABBLE_MASK (0x04u)
#define CSL_USB_INTRUSB_RESET_BABBLE_SHIFT (0x02u)
#define CSL_USB_INTRUSB_RESET_BABBLE_RESETVAL (0x00u)

#define CSL_USB_INTRUSB_RESUME_MASK      (0x02u)
#define CSL_USB_INTRUSB_RESUME_SHIFT     (0x01u)
#define CSL_USB_INTRUSB_RESUME_RESETVAL  (0x00u)

#define CSL_USB_INTRUSB_SUSPEND_MASK     (0x01u)
#define CSL_USB_INTRUSB_SUSPEND_SHIFT    (0x00u)
#define CSL_USB_INTRUSB_SUSPEND_RESETVAL (0x00u)

#define CSL_USB_INTRUSB_RESETVAL         (0x00u)

/* INTRUSBE */

#define CSL_USB_INTRUSBE_VBUSERR_MASK    (0x80u)
#define CSL_USB_INTRUSBE_VBUSERR_SHIFT   (0x07u)
#define CSL_USB_INTRUSBE_VBUSERR_RESETVAL (0x00u)

#define CSL_USB_INTRUSBE_SESSREQ_MASK    (0x40u)
#define CSL_USB_INTRUSBE_SESSREQ_SHIFT   (0x06u)
#define CSL_USB_INTRUSBE_SESSREQ_RESETVAL (0x00u)

#define CSL_USB_INTRUSBE_DISCON_MASK     (0x20u)
#define CSL_USB_INTRUSBE_DISCON_SHIFT    (0x05u)
#define CSL_USB_INTRUSBE_DISCON_RESETVAL (0x00u)

#define CSL_USB_INTRUSBE_CONN_MASK       (0x10u)
#define CSL_USB_INTRUSBE_CONN_SHIFT      (0x04u)
#define CSL_USB_INTRUSBE_CONN_RESETVAL   (0x00u)

#define CSL_USB_INTRUSBE_SOF_MASK        (0x08u)
#define CSL_USB_INTRUSBE_SOF_SHIFT       (0x03u)
#define CSL_USB_INTRUSBE_SOF_RESETVAL    (0x00u)

#define CSL_USB_INTRUSBE_RESET_BABBLE_MASK (0x04u)
#define CSL_USB_INTRUSBE_RESET_BABBLE_SHIFT (0x02u)
#define CSL_USB_INTRUSBE_RESET_BABBLE_RESETVAL (0x01u)

#define CSL_USB_INTRUSBE_RESUME_MASK     (0x02u)
#define CSL_USB_INTRUSBE_RESUME_SHIFT    (0x01u)
#define CSL_USB_INTRUSBE_RESUME_RESETVAL (0x01u)

#define CSL_USB_INTRUSBE_SUSPEND_MASK    (0x01u)
#define CSL_USB_INTRUSBE_SUSPEND_SHIFT   (0x00u)
#define CSL_USB_INTRUSBE_SUSPEND_RESETVAL (0x00u)

#define CSL_USB_INTRUSBE_RESETVAL        (0x06u)

/* FRAME */

#define CSL_USB_FRAME_FRAMENUMBER_MASK   (0x07FFu)
#define CSL_USB_FRAME_FRAMENUMBER_SHIFT  (0x0000u)
#define CSL_USB_FRAME_FRAMENUMBER_RESETVAL (0x0000u)

#define CSL_USB_FRAME_RESETVAL           (0x0000u)

/* INDEX */

#define CSL_USB_INDEX_EPSEL_MASK         (0x0Fu)
#define CSL_USB_INDEX_EPSEL_SHIFT        (0x00u)
#define CSL_USB_INDEX_EPSEL_RESETVAL     (0x00u)

#define CSL_USB_INDEX_RESETVAL           (0x00u)

/* TESTMODE */

#define CSL_USB_TESTMODE_FORCE_HOST_MASK (0x80u)
#define CSL_USB_TESTMODE_FORCE_HOST_SHIFT (0x07u)
#define CSL_USB_TESTMODE_FORCE_HOST_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_FIFO_ACCESS_MASK (0x40u)
#define CSL_USB_TESTMODE_FIFO_ACCESS_SHIFT (0x06u)
#define CSL_USB_TESTMODE_FIFO_ACCESS_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_FORCE_FS_MASK   (0x20u)
#define CSL_USB_TESTMODE_FORCE_FS_SHIFT  (0x05u)
#define CSL_USB_TESTMODE_FORCE_FS_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_FORCE_HS_MASK   (0x10u)
#define CSL_USB_TESTMODE_FORCE_HS_SHIFT  (0x04u)
#define CSL_USB_TESTMODE_FORCE_HS_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_TEST_PACKET_MASK (0x08u)
#define CSL_USB_TESTMODE_TEST_PACKET_SHIFT (0x03u)
#define CSL_USB_TESTMODE_TEST_PACKET_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_TEST_K_MASK     (0x04u)
#define CSL_USB_TESTMODE_TEST_K_SHIFT    (0x02u)
#define CSL_USB_TESTMODE_TEST_K_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_TEST_J_MASK     (0x02u)
#define CSL_USB_TESTMODE_TEST_J_SHIFT    (0x01u)
#define CSL_USB_TESTMODE_TEST_J_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_TEST_SE0_NAK_MASK (0x01u)
#define CSL_USB_TESTMODE_TEST_SE0_NAK_SHIFT (0x00u)
#define CSL_USB_TESTMODE_TEST_SE0_NAK_RESETVAL (0x00u)

#define CSL_USB_TESTMODE_RESETVAL        (0x00u)

/* TXMAXP */

#define CSL_USB_TXMAXP_MAXPAYLOAD_MASK   (0x07FFu)
#define CSL_USB_TXMAXP_MAXPAYLOAD_SHIFT  (0x0000u)
#define CSL_USB_TXMAXP_MAXPAYLOAD_RESETVAL (0x0000u)

#define CSL_USB_TXMAXP_RESETVAL          (0x0000u)

/* PERI_CSR0 */

#define CSL_USB_PERI_CSR0_FLUSHFIFO_MASK (0x0100u)
#define CSL_USB_PERI_CSR0_FLUSHFIFO_SHIFT (0x0008u)
#define CSL_USB_PERI_CSR0_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SERV_SETUPEND_MASK (0x0080u)
#define CSL_USB_PERI_CSR0_SERV_SETUPEND_SHIFT (0x0007u)
#define CSL_USB_PERI_CSR0_SERV_SETUPEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_MASK (0x0040u)
#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_SHIFT (0x0006u)
#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SENDSTALL_MASK (0x0020u)
#define CSL_USB_PERI_CSR0_SENDSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_CSR0_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SETUPEND_MASK  (0x0010u)
#define CSL_USB_PERI_CSR0_SETUPEND_SHIFT (0x0004u)
#define CSL_USB_PERI_CSR0_SETUPEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_DATAEND_MASK   (0x0008u)
#define CSL_USB_PERI_CSR0_DATAEND_SHIFT  (0x0003u)
#define CSL_USB_PERI_CSR0_DATAEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SENTSTALL_MASK (0x0004u)
#define CSL_USB_PERI_CSR0_SENTSTALL_SHIFT (0x0002u)
#define CSL_USB_PERI_CSR0_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_TXPKTRDY_MASK  (0x0002u)
#define CSL_USB_PERI_CSR0_TXPKTRDY_SHIFT (0x0001u)
#define CSL_USB_PERI_CSR0_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_RXPKTRDY_MASK  (0x0001u)
#define CSL_USB_PERI_CSR0_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_CSR0_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_RESETVAL       (0x0000u)

/* HOST_CSR0 */

#define CSL_USB_HOST_CSR0_DATATOGWREN_MASK (0x0400u)
#define CSL_USB_HOST_CSR0_DATATOGWREN_SHIFT (0x000Au)
#define CSL_USB_HOST_CSR0_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_DATATOG_MASK   (0x0200u)
#define CSL_USB_HOST_CSR0_DATATOG_SHIFT  (0x0009u)
#define CSL_USB_HOST_CSR0_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_FLUSHFIFO_MASK (0x0100u)
#define CSL_USB_HOST_CSR0_FLUSHFIFO_SHIFT (0x0008u)
#define CSL_USB_HOST_CSR0_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_MASK (0x0080u)
#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_SHIFT (0x0007u)
#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_STATUSPKT_MASK (0x0040u)
#define CSL_USB_HOST_CSR0_STATUSPKT_SHIFT (0x0006u)
#define CSL_USB_HOST_CSR0_STATUSPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_REQPKT_MASK    (0x0020u)
#define CSL_USB_HOST_CSR0_REQPKT_SHIFT   (0x0005u)
#define CSL_USB_HOST_CSR0_REQPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_ERROR_MASK     (0x0010u)
#define CSL_USB_HOST_CSR0_ERROR_SHIFT    (0x0004u)
#define CSL_USB_HOST_CSR0_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_SETUPPKT_MASK  (0x0008u)
#define CSL_USB_HOST_CSR0_SETUPPKT_SHIFT (0x0003u)
#define CSL_USB_HOST_CSR0_SETUPPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RXSTALL_MASK   (0x0004u)
#define CSL_USB_HOST_CSR0_RXSTALL_SHIFT  (0x0002u)
#define CSL_USB_HOST_CSR0_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_TXPKTRDY_MASK  (0x0002u)
#define CSL_USB_HOST_CSR0_TXPKTRDY_SHIFT (0x0001u)
#define CSL_USB_HOST_CSR0_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RXPKTRDY_MASK  (0x0001u)
#define CSL_USB_HOST_CSR0_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_CSR0_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RESETVAL       (0x0000u)

/* PERI_TXCSR */

#define CSL_USB_PERI_TXCSR_AUTOSET_MASK  (0x8000u)
#define CSL_USB_PERI_TXCSR_AUTOSET_SHIFT (0x000Fu)
#define CSL_USB_PERI_TXCSR_AUTOSET_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_ISO_MASK      (0x4000u)
#define CSL_USB_PERI_TXCSR_ISO_SHIFT     (0x000Eu)
#define CSL_USB_PERI_TXCSR_ISO_RESETVAL  (0x0000u)

#define CSL_USB_PERI_TXCSR_MODE_MASK     (0x2000u)
#define CSL_USB_PERI_TXCSR_MODE_SHIFT    (0x000Du)
#define CSL_USB_PERI_TXCSR_MODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_DMAEN_MASK    (0x1000u)
#define CSL_USB_PERI_TXCSR_DMAEN_SHIFT   (0x000Cu)
#define CSL_USB_PERI_TXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FRCDATATOG_MASK (0x0800u)
#define CSL_USB_PERI_TXCSR_FRCDATATOG_SHIFT (0x000Bu)
#define CSL_USB_PERI_TXCSR_FRCDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_DMAMODE_MASK  (0x0400u)
#define CSL_USB_PERI_TXCSR_DMAMODE_SHIFT (0x000Au)
#define CSL_USB_PERI_TXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_CLRDATATOG_MASK (0x0040u)
#define CSL_USB_PERI_TXCSR_CLRDATATOG_SHIFT (0x0006u)
#define CSL_USB_PERI_TXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_SENTSTALL_MASK (0x0020u)
#define CSL_USB_PERI_TXCSR_SENTSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_TXCSR_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_SENDSTALL_MASK (0x0010u)
#define CSL_USB_PERI_TXCSR_SENDSTALL_SHIFT (0x0004u)
#define CSL_USB_PERI_TXCSR_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FLUSHFIFO_MASK (0x0008u)
#define CSL_USB_PERI_TXCSR_FLUSHFIFO_SHIFT (0x0003u)
#define CSL_USB_PERI_TXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_UNDERRUN_MASK (0x0004u)
#define CSL_USB_PERI_TXCSR_UNDERRUN_SHIFT (0x0002u)
#define CSL_USB_PERI_TXCSR_UNDERRUN_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_MASK (0x0002u)
#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_SHIFT (0x0001u)
#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_TXPKTRDY_MASK (0x0001u)
#define CSL_USB_PERI_TXCSR_TXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_TXCSR_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_RESETVAL      (0x0000u)

/* HOST_TXCSR */

#define CSL_USB_HOST_TXCSR_AUTOSET_MASK  (0x8000u)
#define CSL_USB_HOST_TXCSR_AUTOSET_SHIFT (0x000Fu)
#define CSL_USB_HOST_TXCSR_AUTOSET_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_MODE_MASK     (0x2000u)
#define CSL_USB_HOST_TXCSR_MODE_SHIFT    (0x000Du)
#define CSL_USB_HOST_TXCSR_MODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DMAEN_MASK    (0x1000u)
#define CSL_USB_HOST_TXCSR_DMAEN_SHIFT   (0x000Cu)
#define CSL_USB_HOST_TXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FRCDATATOG_MASK (0x0800u)
#define CSL_USB_HOST_TXCSR_FRCDATATOG_SHIFT (0x000Bu)
#define CSL_USB_HOST_TXCSR_FRCDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DMAMODE_MASK  (0x0400u)
#define CSL_USB_HOST_TXCSR_DMAMODE_SHIFT (0x000Au)
#define CSL_USB_HOST_TXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DATATOGWREN_MASK (0x0200u)
#define CSL_USB_HOST_TXCSR_DATATOGWREN_SHIFT (0x0009u)
#define CSL_USB_HOST_TXCSR_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DATATOG_MASK  (0x0100u)
#define CSL_USB_HOST_TXCSR_DATATOG_SHIFT (0x0008u)
#define CSL_USB_HOST_TXCSR_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_MASK (0x0080u)
#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_SHIFT (0x0007u)
#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_CLRDATATOG_MASK (0x0040u)
#define CSL_USB_HOST_TXCSR_CLRDATATOG_SHIFT (0x0006u)
#define CSL_USB_HOST_TXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_RXSTALL_MASK  (0x0020u)
#define CSL_USB_HOST_TXCSR_RXSTALL_SHIFT (0x0005u)
#define CSL_USB_HOST_TXCSR_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_SETUPPKT_MASK (0x0010u)
#define CSL_USB_HOST_TXCSR_SETUPPKT_SHIFT (0x0004u)
#define CSL_USB_HOST_TXCSR_SETUPPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FLUSHFIFO_MASK (0x0008u)
#define CSL_USB_HOST_TXCSR_FLUSHFIFO_SHIFT (0x0003u)
#define CSL_USB_HOST_TXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_ERROR_MASK    (0x0004u)
#define CSL_USB_HOST_TXCSR_ERROR_SHIFT   (0x0002u)
#define CSL_USB_HOST_TXCSR_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_MASK (0x0002u)
#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_SHIFT (0x0001u)
#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_TXPKTRDY_MASK (0x0001u)
#define CSL_USB_HOST_TXCSR_TXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_TXCSR_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_RESETVAL      (0x0000u)

/* RXMAXP */

#define CSL_USB_RXMAXP_MAXPAYLOAD_MASK   (0x07FFu)
#define CSL_USB_RXMAXP_MAXPAYLOAD_SHIFT  (0x0000u)
#define CSL_USB_RXMAXP_MAXPAYLOAD_RESETVAL (0x0000u)

#define CSL_USB_RXMAXP_RESETVAL          (0x0000u)

/* PERI_RXCSR */

#define CSL_USB_PERI_RXCSR_AUTOCLEAR_MASK (0x8000u)
#define CSL_USB_PERI_RXCSR_AUTOCLEAR_SHIFT (0x000Fu)
#define CSL_USB_PERI_RXCSR_AUTOCLEAR_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_ISO_MASK      (0x4000u)
#define CSL_USB_PERI_RXCSR_ISO_SHIFT     (0x000Eu)
#define CSL_USB_PERI_RXCSR_ISO_RESETVAL  (0x0000u)

#define CSL_USB_PERI_RXCSR_DMAEN_MASK    (0x2000u)
#define CSL_USB_PERI_RXCSR_DMAEN_SHIFT   (0x000Du)
#define CSL_USB_PERI_RXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DISNYET_MASK  (0x1000u)
#define CSL_USB_PERI_RXCSR_DISNYET_SHIFT (0x000Cu)
#define CSL_USB_PERI_RXCSR_DISNYET_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DMAMODE_MASK  (0x0800u)
#define CSL_USB_PERI_RXCSR_DMAMODE_SHIFT (0x000Bu)
#define CSL_USB_PERI_RXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_CLRDATATOG_MASK (0x0080u)
#define CSL_USB_PERI_RXCSR_CLRDATATOG_SHIFT (0x0007u)
#define CSL_USB_PERI_RXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_SENTSTALL_MASK (0x0040u)
#define CSL_USB_PERI_RXCSR_SENTSTALL_SHIFT (0x0006u)
#define CSL_USB_PERI_RXCSR_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_SENDSTALL_MASK (0x0020u)
#define CSL_USB_PERI_RXCSR_SENDSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_RXCSR_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_FLUSHFIFO_MASK (0x0010u)
#define CSL_USB_PERI_RXCSR_FLUSHFIFO_SHIFT (0x0004u)
#define CSL_USB_PERI_RXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DATAERROR_MASK (0x0008u)
#define CSL_USB_PERI_RXCSR_DATAERROR_SHIFT (0x0003u)
#define CSL_USB_PERI_RXCSR_DATAERROR_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_OVERRUN_MASK  (0x0004u)
#define CSL_USB_PERI_RXCSR_OVERRUN_SHIFT (0x0002u)
#define CSL_USB_PERI_RXCSR_OVERRUN_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_FIFOFULL_MASK (0x0002u)
#define CSL_USB_PERI_RXCSR_FIFOFULL_SHIFT (0x0001u)
#define CSL_USB_PERI_RXCSR_FIFOFULL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_RXPKTRDY_MASK (0x0001u)
#define CSL_USB_PERI_RXCSR_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_RXCSR_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_RESETVAL      (0x0000u)

/* HOST_RXCSR */

#define CSL_USB_HOST_RXCSR_AUTOCLEAR_MASK (0x8000u)
#define CSL_USB_HOST_RXCSR_AUTOCLEAR_SHIFT (0x000Fu)
#define CSL_USB_HOST_RXCSR_AUTOCLEAR_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_AUTOREQ_MASK  (0x4000u)
#define CSL_USB_HOST_RXCSR_AUTOREQ_SHIFT (0x000Eu)
#define CSL_USB_HOST_RXCSR_AUTOREQ_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DMAEN_MASK    (0x2000u)
#define CSL_USB_HOST_RXCSR_DMAEN_SHIFT   (0x000Du)
#define CSL_USB_HOST_RXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DISNYET_MASK  (0x1000u)
#define CSL_USB_HOST_RXCSR_DISNYET_SHIFT (0x000Cu)
#define CSL_USB_HOST_RXCSR_DISNYET_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DMAMODE_MASK  (0x0800u)
#define CSL_USB_HOST_RXCSR_DMAMODE_SHIFT (0x000Bu)
#define CSL_USB_HOST_RXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATATOGWREN_MASK (0x0400u)
#define CSL_USB_HOST_RXCSR_DATATOGWREN_SHIFT (0x000Au)
#define CSL_USB_HOST_RXCSR_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATATOG_MASK  (0x0200u)
#define CSL_USB_HOST_RXCSR_DATATOG_SHIFT (0x0009u)
#define CSL_USB_HOST_RXCSR_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_CLRDATATOG_MASK (0x0080u)
#define CSL_USB_HOST_RXCSR_CLRDATATOG_SHIFT (0x0007u)
#define CSL_USB_HOST_RXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RXSTALL_MASK  (0x0040u)
#define CSL_USB_HOST_RXCSR_RXSTALL_SHIFT (0x0006u)
#define CSL_USB_HOST_RXCSR_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_REQPKT_MASK   (0x0020u)
#define CSL_USB_HOST_RXCSR_REQPKT_SHIFT  (0x0005u)
#define CSL_USB_HOST_RXCSR_REQPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_FLUSHFIFO_MASK (0x0010u)
#define CSL_USB_HOST_RXCSR_FLUSHFIFO_SHIFT (0x0004u)
#define CSL_USB_HOST_RXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_MASK (0x0008u)
#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_SHIFT (0x0003u)
#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_ERROR_MASK    (0x0004u)
#define CSL_USB_HOST_RXCSR_ERROR_SHIFT   (0x0002u)
#define CSL_USB_HOST_RXCSR_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_FIFOFULL_MASK (0x0002u)
#define CSL_USB_HOST_RXCSR_FIFOFULL_SHIFT (0x0001u)
#define CSL_USB_HOST_RXCSR_FIFOFULL_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RXPKTRDY_MASK (0x0001u)
#define CSL_USB_HOST_RXCSR_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_RXCSR_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RESETVAL      (0x0000u)

/* COUNT0 */

#define CSL_USB_COUNT0_EP0RXCOUNT_MASK   (0x007Fu)
#define CSL_USB_COUNT0_EP0RXCOUNT_SHIFT  (0x0000u)
#define CSL_USB_COUNT0_EP0RXCOUNT_RESETVAL (0x0000u)

#define CSL_USB_COUNT0_RESETVAL          (0x0000u)

/* RXCOUNT */

#define CSL_USB_RXCOUNT_EPRXCOUNT_MASK   (0x1FFFu)
#define CSL_USB_RXCOUNT_EPRXCOUNT_SHIFT  (0x0000u)
#define CSL_USB_RXCOUNT_EPRXCOUNT_RESETVAL (0x0000u)

#define CSL_USB_RXCOUNT_RESETVAL         (0x0000u)

/* HOST_TYPE0 */

#define CSL_USB_HOST_TYPE0_SPEED_MASK    (0xC0u)
#define CSL_USB_HOST_TYPE0_SPEED_SHIFT   (0x06u)
#define CSL_USB_HOST_TYPE0_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_TYPE0_RESETVAL      (0x00u)

/* HOST_TXTYPE */

#define CSL_USB_HOST_TXTYPE_SPEED_MASK   (0xC0u)
#define CSL_USB_HOST_TXTYPE_SPEED_SHIFT  (0x06u)
#define CSL_USB_HOST_TXTYPE_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_PROT_MASK    (0x30u)
#define CSL_USB_HOST_TXTYPE_PROT_SHIFT   (0x04u)
#define CSL_USB_HOST_TXTYPE_PROT_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_TENDPN_MASK  (0x0Fu)
#define CSL_USB_HOST_TXTYPE_TENDPN_SHIFT (0x00u)
#define CSL_USB_HOST_TXTYPE_TENDPN_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_RESETVAL     (0x00u)

/* HOST_NAKLIMIT0 */

#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_MASK (0x1Fu)
#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_NAKLIMIT0_RESETVAL  (0x00u)

/* HOST_TXINTERVAL */

#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_MASK (0xFFu)
#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_TXINTERVAL_RESETVAL (0x00u)

/* HOST_RXTYPE */

#define CSL_USB_HOST_RXTYPE_SPEED_MASK   (0xC0u)
#define CSL_USB_HOST_RXTYPE_SPEED_SHIFT  (0x06u)
#define CSL_USB_HOST_RXTYPE_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_PROT_MASK    (0x30u)
#define CSL_USB_HOST_RXTYPE_PROT_SHIFT   (0x04u)
#define CSL_USB_HOST_RXTYPE_PROT_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_RENDPN_MASK  (0x0Fu)
#define CSL_USB_HOST_RXTYPE_RENDPN_SHIFT (0x00u)
#define CSL_USB_HOST_RXTYPE_RENDPN_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_RESETVAL     (0x00u)

/* HOST_RXINTERVAL */

#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_MASK (0xFFu)
#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_RXINTERVAL_RESETVAL (0x00u)

/* CONFIGDATA */

#define CSL_USB_CONFIGDATA_MPRXE_MASK    (0x80u)
#define CSL_USB_CONFIGDATA_MPRXE_SHIFT   (0x07u)
#define CSL_USB_CONFIGDATA_MPRXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_MPTXE_MASK    (0x40u)
#define CSL_USB_CONFIGDATA_MPTXE_SHIFT   (0x06u)
#define CSL_USB_CONFIGDATA_MPTXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_BIGENDIAN_MASK (0x20u)
#define CSL_USB_CONFIGDATA_BIGENDIAN_SHIFT (0x05u)
#define CSL_USB_CONFIGDATA_BIGENDIAN_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_HBRXE_MASK    (0x10u)
#define CSL_USB_CONFIGDATA_HBRXE_SHIFT   (0x04u)
#define CSL_USB_CONFIGDATA_HBRXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_HBTXE_MASK    (0x08u)
#define CSL_USB_CONFIGDATA_HBTXE_SHIFT   (0x03u)
#define CSL_USB_CONFIGDATA_HBTXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_DYNFIFO_MASK  (0x04u)
#define CSL_USB_CONFIGDATA_DYNFIFO_SHIFT (0x02u)
#define CSL_USB_CONFIGDATA_DYNFIFO_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_SOFTCONE_MASK (0x02u)
#define CSL_USB_CONFIGDATA_SOFTCONE_SHIFT (0x01u)
#define CSL_USB_CONFIGDATA_SOFTCONE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_MASK (0x01u)
#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_SHIFT (0x00u)
#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_RESETVAL      (0x00u)

/* FIFOSIZE */

#define CSL_USB_FIFOSIZE_RXFIFOSZ_MASK   (0xF0u)
#define CSL_USB_FIFOSIZE_RXFIFOSZ_SHIFT  (0x04u)
#define CSL_USB_FIFOSIZE_RXFIFOSZ_RESETVAL (0x00u)

#define CSL_USB_FIFOSIZE_TXFIFOSZ_MASK   (0x0Fu)
#define CSL_USB_FIFOSIZE_TXFIFOSZ_SHIFT  (0x00u)
#define CSL_USB_FIFOSIZE_TXFIFOSZ_RESETVAL (0x00u)

#define CSL_USB_FIFOSIZE_RESETVAL        (0x00u)

/* DEVCTL */

#define CSL_USB_DEVCTL_BDEVICE_MASK      (0x80u)
#define CSL_USB_DEVCTL_BDEVICE_SHIFT     (0x07u)
#define CSL_USB_DEVCTL_BDEVICE_RESETVAL  (0x00u)

#define CSL_USB_DEVCTL_FSDEV_MASK        (0x40u)
#define CSL_USB_DEVCTL_FSDEV_SHIFT       (0x06u)
#define CSL_USB_DEVCTL_FSDEV_RESETVAL    (0x00u)

#define CSL_USB_DEVCTL_LSDEV_MASK        (0x20u)
#define CSL_USB_DEVCTL_LSDEV_SHIFT       (0x05u)
#define CSL_USB_DEVCTL_LSDEV_RESETVAL    (0x00u)

#define CSL_USB_DEVCTL_VBUS_MASK         (0x18u)
#define CSL_USB_DEVCTL_VBUS_SHIFT        (0x03u)
#define CSL_USB_DEVCTL_VBUS_RESETVAL     (0x00u)

#define CSL_USB_DEVCTL_HOSTMODE_MASK     (0x04u)
#define CSL_USB_DEVCTL_HOSTMODE_SHIFT    (0x02u)
#define CSL_USB_DEVCTL_HOSTMODE_RESETVAL (0x00u)

#define CSL_USB_DEVCTL_HOSTREQ_MASK      (0x02u)
#define CSL_USB_DEVCTL_HOSTREQ_SHIFT     (0x01u)
#define CSL_USB_DEVCTL_HOSTREQ_RESETVAL  (0x00u)

#define CSL_USB_DEVCTL_SESSION_MASK      (0x01u)
#define CSL_USB_DEVCTL_SESSION_SHIFT     (0x00u)
#define CSL_USB_DEVCTL_SESSION_RESETVAL  (0x00u)

#define CSL_USB_DEVCTL_RESETVAL          (0x00u)

/* TXFIFOSZ */

#define CSL_USB_TXFIFOSZ_DPB_MASK        (0x10u)
#define CSL_USB_TXFIFOSZ_DPB_SHIFT       (0x04u)
#define CSL_USB_TXFIFOSZ_DPB_RESETVAL    (0x00u)

#define CSL_USB_TXFIFOSZ_SZ_MASK         (0x0Fu)
#define CSL_USB_TXFIFOSZ_SZ_SHIFT        (0x00u)
#define CSL_USB_TXFIFOSZ_SZ_RESETVAL     (0x00u)

#define CSL_USB_TXFIFOSZ_RESETVAL        (0x00u)

/* RXFIFOSZ */

#define CSL_USB_RXFIFOSZ_DPB_MASK        (0x10u)
#define CSL_USB_RXFIFOSZ_DPB_SHIFT       (0x04u)
#define CSL_USB_RXFIFOSZ_DPB_RESETVAL    (0x00u)

#define CSL_USB_RXFIFOSZ_SZ_MASK         (0x0Fu)
#define CSL_USB_RXFIFOSZ_SZ_SHIFT        (0x00u)
#define CSL_USB_RXFIFOSZ_SZ_RESETVAL     (0x00u)

#define CSL_USB_RXFIFOSZ_RESETVAL        (0x00u)

/* TXFIFOADDR */

#define CSL_USB_TXFIFOADDR_ADDR_MASK     (0x1FFFu)
#define CSL_USB_TXFIFOADDR_ADDR_SHIFT    (0x0000u)
#define CSL_USB_TXFIFOADDR_ADDR_RESETVAL (0x0000u)

#define CSL_USB_TXFIFOADDR_RESETVAL      (0x0000u)

/* RXFIFOADDR */

#define CSL_USB_RXFIFOADDR_ADDR_MASK     (0x1FFFu)
#define CSL_USB_RXFIFOADDR_ADDR_SHIFT    (0x0000u)
#define CSL_USB_RXFIFOADDR_ADDR_RESETVAL (0x0000u)

#define CSL_USB_RXFIFOADDR_RESETVAL      (0x0000u)

/* TXFUNCADDR */

#define CSL_USB_TXFUNCADDR_FUNCADDR_MASK (0x7Fu)
#define CSL_USB_TXFUNCADDR_FUNCADDR_SHIFT (0x00u)
#define CSL_USB_TXFUNCADDR_FUNCADDR_RESETVAL (0x00u)

#define CSL_USB_TXFUNCADDR_RESETVAL      (0x00u)

/* TXHUBADDR */

#define CSL_USB_TXHUBADDR_MULT_TRANS_MASK (0x80u)
#define CSL_USB_TXHUBADDR_MULT_TRANS_SHIFT (0x07u)
#define CSL_USB_TXHUBADDR_MULT_TRANS_RESETVAL (0x00u)

#define CSL_USB_TXHUBADDR_HUBADDR_MASK   (0x7Fu)
#define CSL_USB_TXHUBADDR_HUBADDR_SHIFT  (0x00u)
#define CSL_USB_TXHUBADDR_HUBADDR_RESETVAL (0x00u)

#define CSL_USB_TXHUBADDR_RESETVAL       (0x00u)

/* TXHUBPORT */

#define CSL_USB_TXHUBPORT_HUBPORT_MASK   (0x7Fu)
#define CSL_USB_TXHUBPORT_HUBPORT_SHIFT  (0x00u)
#define CSL_USB_TXHUBPORT_HUBPORT_RESETVAL (0x00u)

#define CSL_USB_TXHUBPORT_RESETVAL       (0x00u)

/* RXFUNCADDR */

#define CSL_USB_RXFUNCADDR_FUNCADDR_MASK (0x7Fu)
#define CSL_USB_RXFUNCADDR_FUNCADDR_SHIFT (0x00u)
#define CSL_USB_RXFUNCADDR_FUNCADDR_RESETVAL (0x00u)

#define CSL_USB_RXFUNCADDR_RESETVAL      (0x00u)

/* RXHUBADDR */

#define CSL_USB_RXHUBADDR_MULT_TRANS_MASK (0x80u)
#define CSL_USB_RXHUBADDR_MULT_TRANS_SHIFT (0x07u)
#define CSL_USB_RXHUBADDR_MULT_TRANS_RESETVAL (0x00u)

#define CSL_USB_RXHUBADDR_HUBADDR_MASK   (0x7Fu)
#define CSL_USB_RXHUBADDR_HUBADDR_SHIFT  (0x00u)
#define CSL_USB_RXHUBADDR_HUBADDR_RESETVAL (0x00u)

#define CSL_USB_RXHUBADDR_RESETVAL       (0x00u)

/* RXHUBPORT */

#define CSL_USB_RXHUBPORT_HUBPORT_MASK   (0x7Fu)
#define CSL_USB_RXHUBPORT_HUBPORT_SHIFT  (0x00u)
#define CSL_USB_RXHUBPORT_HUBPORT_RESETVAL (0x00u)

#define CSL_USB_RXHUBPORT_RESETVAL       (0x00u)

/* PERI_CSR0 */

#define CSL_USB_PERI_CSR0_FLUSHFIFO_MASK (0x0100u)
#define CSL_USB_PERI_CSR0_FLUSHFIFO_SHIFT (0x0008u)
#define CSL_USB_PERI_CSR0_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SERV_SETUPEND_MASK (0x0080u)
#define CSL_USB_PERI_CSR0_SERV_SETUPEND_SHIFT (0x0007u)
#define CSL_USB_PERI_CSR0_SERV_SETUPEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_MASK (0x0040u)
#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_SHIFT (0x0006u)
#define CSL_USB_PERI_CSR0_SERV_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SENDSTALL_MASK (0x0020u)
#define CSL_USB_PERI_CSR0_SENDSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_CSR0_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SETUPEND_MASK  (0x0010u)
#define CSL_USB_PERI_CSR0_SETUPEND_SHIFT (0x0004u)
#define CSL_USB_PERI_CSR0_SETUPEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_DATAEND_MASK   (0x0008u)
#define CSL_USB_PERI_CSR0_DATAEND_SHIFT  (0x0003u)
#define CSL_USB_PERI_CSR0_DATAEND_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_SENTSTALL_MASK (0x0004u)
#define CSL_USB_PERI_CSR0_SENTSTALL_SHIFT (0x0002u)
#define CSL_USB_PERI_CSR0_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_TXPKTRDY_MASK  (0x0002u)
#define CSL_USB_PERI_CSR0_TXPKTRDY_SHIFT (0x0001u)
#define CSL_USB_PERI_CSR0_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_RXPKTRDY_MASK  (0x0001u)
#define CSL_USB_PERI_CSR0_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_CSR0_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_CSR0_RESETVAL       (0x0000u)

/* HOST_CSR0 */

#define CSL_USB_HOST_CSR0_DATATOGWREN_MASK (0x0400u)
#define CSL_USB_HOST_CSR0_DATATOGWREN_SHIFT (0x000Au)
#define CSL_USB_HOST_CSR0_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_DATATOG_MASK   (0x0200u)
#define CSL_USB_HOST_CSR0_DATATOG_SHIFT  (0x0009u)
#define CSL_USB_HOST_CSR0_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_FLUSHFIFO_MASK (0x0100u)
#define CSL_USB_HOST_CSR0_FLUSHFIFO_SHIFT (0x0008u)
#define CSL_USB_HOST_CSR0_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_MASK (0x0080u)
#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_SHIFT (0x0007u)
#define CSL_USB_HOST_CSR0_NAK_TIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_STATUSPKT_MASK (0x0040u)
#define CSL_USB_HOST_CSR0_STATUSPKT_SHIFT (0x0006u)
#define CSL_USB_HOST_CSR0_STATUSPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_REQPKT_MASK    (0x0020u)
#define CSL_USB_HOST_CSR0_REQPKT_SHIFT   (0x0005u)
#define CSL_USB_HOST_CSR0_REQPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_ERROR_MASK     (0x0010u)
#define CSL_USB_HOST_CSR0_ERROR_SHIFT    (0x0004u)
#define CSL_USB_HOST_CSR0_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_SETUPPKT_MASK  (0x0008u)
#define CSL_USB_HOST_CSR0_SETUPPKT_SHIFT (0x0003u)
#define CSL_USB_HOST_CSR0_SETUPPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RXSTALL_MASK   (0x0004u)
#define CSL_USB_HOST_CSR0_RXSTALL_SHIFT  (0x0002u)
#define CSL_USB_HOST_CSR0_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_TXPKTRDY_MASK  (0x0002u)
#define CSL_USB_HOST_CSR0_TXPKTRDY_SHIFT (0x0001u)
#define CSL_USB_HOST_CSR0_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RXPKTRDY_MASK  (0x0001u)
#define CSL_USB_HOST_CSR0_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_CSR0_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_CSR0_RESETVAL       (0x0000u)

/* PERI_TXCSR */

#define CSL_USB_PERI_TXCSR_AUTOSET_MASK  (0x8000u)
#define CSL_USB_PERI_TXCSR_AUTOSET_SHIFT (0x000Fu)
#define CSL_USB_PERI_TXCSR_AUTOSET_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_ISO_MASK      (0x4000u)
#define CSL_USB_PERI_TXCSR_ISO_SHIFT     (0x000Eu)
#define CSL_USB_PERI_TXCSR_ISO_RESETVAL  (0x0000u)

#define CSL_USB_PERI_TXCSR_MODE_MASK     (0x2000u)
#define CSL_USB_PERI_TXCSR_MODE_SHIFT    (0x000Du)
#define CSL_USB_PERI_TXCSR_MODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_DMAEN_MASK    (0x1000u)
#define CSL_USB_PERI_TXCSR_DMAEN_SHIFT   (0x000Cu)
#define CSL_USB_PERI_TXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FRCDATATOG_MASK (0x0800u)
#define CSL_USB_PERI_TXCSR_FRCDATATOG_SHIFT (0x000Bu)
#define CSL_USB_PERI_TXCSR_FRCDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_DMAMODE_MASK  (0x0400u)
#define CSL_USB_PERI_TXCSR_DMAMODE_SHIFT (0x000Au)
#define CSL_USB_PERI_TXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_CLRDATATOG_MASK (0x0040u)
#define CSL_USB_PERI_TXCSR_CLRDATATOG_SHIFT (0x0006u)
#define CSL_USB_PERI_TXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_SENTSTALL_MASK (0x0020u)
#define CSL_USB_PERI_TXCSR_SENTSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_TXCSR_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_SENDSTALL_MASK (0x0010u)
#define CSL_USB_PERI_TXCSR_SENDSTALL_SHIFT (0x0004u)
#define CSL_USB_PERI_TXCSR_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FLUSHFIFO_MASK (0x0008u)
#define CSL_USB_PERI_TXCSR_FLUSHFIFO_SHIFT (0x0003u)
#define CSL_USB_PERI_TXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_UNDERRUN_MASK (0x0004u)
#define CSL_USB_PERI_TXCSR_UNDERRUN_SHIFT (0x0002u)
#define CSL_USB_PERI_TXCSR_UNDERRUN_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_MASK (0x0002u)
#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_SHIFT (0x0001u)
#define CSL_USB_PERI_TXCSR_FIFONOTEMPTY_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_TXPKTRDY_MASK (0x0001u)
#define CSL_USB_PERI_TXCSR_TXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_TXCSR_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_TXCSR_RESETVAL      (0x0000u)

/* HOST_TXCSR */

#define CSL_USB_HOST_TXCSR_AUTOSET_MASK  (0x8000u)
#define CSL_USB_HOST_TXCSR_AUTOSET_SHIFT (0x000Fu)
#define CSL_USB_HOST_TXCSR_AUTOSET_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_MODE_MASK     (0x2000u)
#define CSL_USB_HOST_TXCSR_MODE_SHIFT    (0x000Du)
#define CSL_USB_HOST_TXCSR_MODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DMAEN_MASK    (0x1000u)
#define CSL_USB_HOST_TXCSR_DMAEN_SHIFT   (0x000Cu)
#define CSL_USB_HOST_TXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FRCDATATOG_MASK (0x0800u)
#define CSL_USB_HOST_TXCSR_FRCDATATOG_SHIFT (0x000Bu)
#define CSL_USB_HOST_TXCSR_FRCDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DMAMODE_MASK  (0x0400u)
#define CSL_USB_HOST_TXCSR_DMAMODE_SHIFT (0x000Au)
#define CSL_USB_HOST_TXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DATATOGWREN_MASK (0x0200u)
#define CSL_USB_HOST_TXCSR_DATATOGWREN_SHIFT (0x0009u)
#define CSL_USB_HOST_TXCSR_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_DATATOG_MASK  (0x0100u)
#define CSL_USB_HOST_TXCSR_DATATOG_SHIFT (0x0008u)
#define CSL_USB_HOST_TXCSR_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_MASK (0x0080u)
#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_SHIFT (0x0007u)
#define CSL_USB_HOST_TXCSR_NAK_TIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_CLRDATATOG_MASK (0x0040u)
#define CSL_USB_HOST_TXCSR_CLRDATATOG_SHIFT (0x0006u)
#define CSL_USB_HOST_TXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_RXSTALL_MASK  (0x0020u)
#define CSL_USB_HOST_TXCSR_RXSTALL_SHIFT (0x0005u)
#define CSL_USB_HOST_TXCSR_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_SETUPPKT_MASK (0x0010u)
#define CSL_USB_HOST_TXCSR_SETUPPKT_SHIFT (0x0004u)
#define CSL_USB_HOST_TXCSR_SETUPPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FLUSHFIFO_MASK (0x0008u)
#define CSL_USB_HOST_TXCSR_FLUSHFIFO_SHIFT (0x0003u)
#define CSL_USB_HOST_TXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_ERROR_MASK    (0x0004u)
#define CSL_USB_HOST_TXCSR_ERROR_SHIFT   (0x0002u)
#define CSL_USB_HOST_TXCSR_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_MASK (0x0002u)
#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_SHIFT (0x0001u)
#define CSL_USB_HOST_TXCSR_FIFONOTEMPTY_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_TXPKTRDY_MASK (0x0001u)
#define CSL_USB_HOST_TXCSR_TXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_TXCSR_TXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_TXCSR_RESETVAL      (0x0000u)

/* RXMAXP */

#define CSL_USB_RXMAXP_MAXPAYLOAD_MASK   (0x07FFu)
#define CSL_USB_RXMAXP_MAXPAYLOAD_SHIFT  (0x0000u)
#define CSL_USB_RXMAXP_MAXPAYLOAD_RESETVAL (0x0000u)

#define CSL_USB_RXMAXP_RESETVAL          (0x0000u)

/* PERI_RXCSR */

#define CSL_USB_PERI_RXCSR_AUTOCLEAR_MASK (0x8000u)
#define CSL_USB_PERI_RXCSR_AUTOCLEAR_SHIFT (0x000Fu)
#define CSL_USB_PERI_RXCSR_AUTOCLEAR_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_ISO_MASK      (0x4000u)
#define CSL_USB_PERI_RXCSR_ISO_SHIFT     (0x000Eu)
#define CSL_USB_PERI_RXCSR_ISO_RESETVAL  (0x0000u)

#define CSL_USB_PERI_RXCSR_DMAEN_MASK    (0x2000u)
#define CSL_USB_PERI_RXCSR_DMAEN_SHIFT   (0x000Du)
#define CSL_USB_PERI_RXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DISNYET_MASK  (0x1000u)
#define CSL_USB_PERI_RXCSR_DISNYET_SHIFT (0x000Cu)
#define CSL_USB_PERI_RXCSR_DISNYET_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DMAMODE_MASK  (0x0800u)
#define CSL_USB_PERI_RXCSR_DMAMODE_SHIFT (0x000Bu)
#define CSL_USB_PERI_RXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_CLRDATATOG_MASK (0x0080u)
#define CSL_USB_PERI_RXCSR_CLRDATATOG_SHIFT (0x0007u)
#define CSL_USB_PERI_RXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_SENTSTALL_MASK (0x0040u)
#define CSL_USB_PERI_RXCSR_SENTSTALL_SHIFT (0x0006u)
#define CSL_USB_PERI_RXCSR_SENTSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_SENDSTALL_MASK (0x0020u)
#define CSL_USB_PERI_RXCSR_SENDSTALL_SHIFT (0x0005u)
#define CSL_USB_PERI_RXCSR_SENDSTALL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_FLUSHFIFO_MASK (0x0010u)
#define CSL_USB_PERI_RXCSR_FLUSHFIFO_SHIFT (0x0004u)
#define CSL_USB_PERI_RXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_DATAERROR_MASK (0x0008u)
#define CSL_USB_PERI_RXCSR_DATAERROR_SHIFT (0x0003u)
#define CSL_USB_PERI_RXCSR_DATAERROR_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_OVERRUN_MASK  (0x0004u)
#define CSL_USB_PERI_RXCSR_OVERRUN_SHIFT (0x0002u)
#define CSL_USB_PERI_RXCSR_OVERRUN_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_FIFOFULL_MASK (0x0002u)
#define CSL_USB_PERI_RXCSR_FIFOFULL_SHIFT (0x0001u)
#define CSL_USB_PERI_RXCSR_FIFOFULL_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_RXPKTRDY_MASK (0x0001u)
#define CSL_USB_PERI_RXCSR_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_PERI_RXCSR_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_PERI_RXCSR_RESETVAL      (0x0000u)

/* HOST_RXCSR */

#define CSL_USB_HOST_RXCSR_AUTOCLEAR_MASK (0x8000u)
#define CSL_USB_HOST_RXCSR_AUTOCLEAR_SHIFT (0x000Fu)
#define CSL_USB_HOST_RXCSR_AUTOCLEAR_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_AUTOREQ_MASK  (0x4000u)
#define CSL_USB_HOST_RXCSR_AUTOREQ_SHIFT (0x000Eu)
#define CSL_USB_HOST_RXCSR_AUTOREQ_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DMAEN_MASK    (0x2000u)
#define CSL_USB_HOST_RXCSR_DMAEN_SHIFT   (0x000Du)
#define CSL_USB_HOST_RXCSR_DMAEN_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DISNYET_MASK  (0x1000u)
#define CSL_USB_HOST_RXCSR_DISNYET_SHIFT (0x000Cu)
#define CSL_USB_HOST_RXCSR_DISNYET_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DMAMODE_MASK  (0x0800u)
#define CSL_USB_HOST_RXCSR_DMAMODE_SHIFT (0x000Bu)
#define CSL_USB_HOST_RXCSR_DMAMODE_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATATOGWREN_MASK (0x0400u)
#define CSL_USB_HOST_RXCSR_DATATOGWREN_SHIFT (0x000Au)
#define CSL_USB_HOST_RXCSR_DATATOGWREN_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATATOG_MASK  (0x0200u)
#define CSL_USB_HOST_RXCSR_DATATOG_SHIFT (0x0009u)
#define CSL_USB_HOST_RXCSR_DATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_CLRDATATOG_MASK (0x0080u)
#define CSL_USB_HOST_RXCSR_CLRDATATOG_SHIFT (0x0007u)
#define CSL_USB_HOST_RXCSR_CLRDATATOG_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RXSTALL_MASK  (0x0040u)
#define CSL_USB_HOST_RXCSR_RXSTALL_SHIFT (0x0006u)
#define CSL_USB_HOST_RXCSR_RXSTALL_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_REQPKT_MASK   (0x0020u)
#define CSL_USB_HOST_RXCSR_REQPKT_SHIFT  (0x0005u)
#define CSL_USB_HOST_RXCSR_REQPKT_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_FLUSHFIFO_MASK (0x0010u)
#define CSL_USB_HOST_RXCSR_FLUSHFIFO_SHIFT (0x0004u)
#define CSL_USB_HOST_RXCSR_FLUSHFIFO_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_MASK (0x0008u)
#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_SHIFT (0x0003u)
#define CSL_USB_HOST_RXCSR_DATAERR_NAKTIMEOUT_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_ERROR_MASK    (0x0004u)
#define CSL_USB_HOST_RXCSR_ERROR_SHIFT   (0x0002u)
#define CSL_USB_HOST_RXCSR_ERROR_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_FIFOFULL_MASK (0x0002u)
#define CSL_USB_HOST_RXCSR_FIFOFULL_SHIFT (0x0001u)
#define CSL_USB_HOST_RXCSR_FIFOFULL_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RXPKTRDY_MASK (0x0001u)
#define CSL_USB_HOST_RXCSR_RXPKTRDY_SHIFT (0x0000u)
#define CSL_USB_HOST_RXCSR_RXPKTRDY_RESETVAL (0x0000u)

#define CSL_USB_HOST_RXCSR_RESETVAL      (0x0000u)

/* COUNT0 */

#define CSL_USB_COUNT0_EP0RXCOUNT_MASK   (0x007Fu)
#define CSL_USB_COUNT0_EP0RXCOUNT_SHIFT  (0x0000u)
#define CSL_USB_COUNT0_EP0RXCOUNT_RESETVAL (0x0000u)

#define CSL_USB_COUNT0_RESETVAL          (0x0000u)

/* RXCOUNT */

#define CSL_USB_RXCOUNT_EPRXCOUNT_MASK   (0x1FFFu)
#define CSL_USB_RXCOUNT_EPRXCOUNT_SHIFT  (0x0000u)
#define CSL_USB_RXCOUNT_EPRXCOUNT_RESETVAL (0x0000u)

#define CSL_USB_RXCOUNT_RESETVAL         (0x0000u)

/* HOST_TYPE0 */

#define CSL_USB_HOST_TYPE0_SPEED_MASK    (0xC0u)
#define CSL_USB_HOST_TYPE0_SPEED_SHIFT   (0x06u)
#define CSL_USB_HOST_TYPE0_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_TYPE0_RESETVAL      (0x00u)

/* HOST_TXTYPE */

#define CSL_USB_HOST_TXTYPE_SPEED_MASK   (0xC0u)
#define CSL_USB_HOST_TXTYPE_SPEED_SHIFT  (0x06u)
#define CSL_USB_HOST_TXTYPE_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_PROT_MASK    (0x30u)
#define CSL_USB_HOST_TXTYPE_PROT_SHIFT   (0x04u)
#define CSL_USB_HOST_TXTYPE_PROT_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_TENDPN_MASK  (0x0Fu)
#define CSL_USB_HOST_TXTYPE_TENDPN_SHIFT (0x00u)
#define CSL_USB_HOST_TXTYPE_TENDPN_RESETVAL (0x00u)

#define CSL_USB_HOST_TXTYPE_RESETVAL     (0x00u)

/* HOST_NAKLIMIT0 */

#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_MASK (0x1Fu)
#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_NAKLIMIT0_EP0NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_NAKLIMIT0_RESETVAL  (0x00u)

/* HOST_TXINTERVAL */

#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_MASK (0xFFu)
#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_TXINTERVAL_POLINTVL_NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_TXINTERVAL_RESETVAL (0x00u)

/* HOST_RXTYPE */

#define CSL_USB_HOST_RXTYPE_SPEED_MASK   (0xC0u)
#define CSL_USB_HOST_RXTYPE_SPEED_SHIFT  (0x06u)
#define CSL_USB_HOST_RXTYPE_SPEED_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_PROT_MASK    (0x30u)
#define CSL_USB_HOST_RXTYPE_PROT_SHIFT   (0x04u)
#define CSL_USB_HOST_RXTYPE_PROT_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_RENDPN_MASK  (0x0Fu)
#define CSL_USB_HOST_RXTYPE_RENDPN_SHIFT (0x00u)
#define CSL_USB_HOST_RXTYPE_RENDPN_RESETVAL (0x00u)

#define CSL_USB_HOST_RXTYPE_RESETVAL     (0x00u)

/* HOST_RXINTERVAL */

#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_MASK (0xFFu)
#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_SHIFT (0x00u)
#define CSL_USB_HOST_RXINTERVAL_POLINTVL_NAKLIMIT_RESETVAL (0x00u)

#define CSL_USB_HOST_RXINTERVAL_RESETVAL (0x00u)

/* CONFIGDATA */

#define CSL_USB_CONFIGDATA_MPRXE_MASK    (0x80u)
#define CSL_USB_CONFIGDATA_MPRXE_SHIFT   (0x07u)
#define CSL_USB_CONFIGDATA_MPRXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_MPTXE_MASK    (0x40u)
#define CSL_USB_CONFIGDATA_MPTXE_SHIFT   (0x06u)
#define CSL_USB_CONFIGDATA_MPTXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_BIGENDIAN_MASK (0x20u)
#define CSL_USB_CONFIGDATA_BIGENDIAN_SHIFT (0x05u)
#define CSL_USB_CONFIGDATA_BIGENDIAN_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_HBRXE_MASK    (0x10u)
#define CSL_USB_CONFIGDATA_HBRXE_SHIFT   (0x04u)
#define CSL_USB_CONFIGDATA_HBRXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_HBTXE_MASK    (0x08u)
#define CSL_USB_CONFIGDATA_HBTXE_SHIFT   (0x03u)
#define CSL_USB_CONFIGDATA_HBTXE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_DYNFIFO_MASK  (0x04u)
#define CSL_USB_CONFIGDATA_DYNFIFO_SHIFT (0x02u)
#define CSL_USB_CONFIGDATA_DYNFIFO_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_SOFTCONE_MASK (0x02u)
#define CSL_USB_CONFIGDATA_SOFTCONE_SHIFT (0x01u)
#define CSL_USB_CONFIGDATA_SOFTCONE_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_MASK (0x01u)
#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_SHIFT (0x00u)
#define CSL_USB_CONFIGDATA_UTMIDATAWIDTH_RESETVAL (0x00u)

#define CSL_USB_CONFIGDATA_RESETVAL      (0x00u)

/* FIFOSIZE */

#define CSL_USB_FIFOSIZE_RXFIFOSZ_MASK   (0xF0u)
#define CSL_USB_FIFOSIZE_RXFIFOSZ_SHIFT  (0x04u)
#define CSL_USB_FIFOSIZE_RXFIFOSZ_RESETVAL (0x00u)

#define CSL_USB_FIFOSIZE_TXFIFOSZ_MASK   (0x0Fu)
#define CSL_USB_FIFOSIZE_TXFIFOSZ_SHIFT  (0x00u)
#define CSL_USB_FIFOSIZE_TXFIFOSZ_RESETVAL (0x00u)

#define CSL_USB_FIFOSIZE_RESETVAL        (0x00u)

// OTG_SYSCONFIG register
#define MIDLEMODE       12
#define OTG_SYSCONF_M_FORCESTDBY    (0 << MIDLEMODE)
#define OTG_SYSCONF_M_NOSTDBY       (1 << MIDLEMODE)
#define OTG_SYSCONF_M_SMARTSTDBY    (2 << MIDLEMODE)
#define OTG_SYSCONF_M_MASK          (3 << MIDLEMODE)

#define SIDLEMODE       3
#define OTG_SYSCONF_S_FORCEIDLE    (0 << SIDLEMODE)
#define OTG_SYSCONF_S_NOIDLE       (1 << SIDLEMODE)
#define OTG_SYSCONF_S_SMARTIDLE    (2 << SIDLEMODE)
#define OTG_SYSCONF_S_MASK         (3 << SIDLEMODE)

#define OTG_SYSCONF_ENABLEWAKEUP    (1 << 2)
#define OTG_SYSCONF_SOFTRESET       (1 << 1)
#define OTG_SYSCONF_AUTOIDLE        (1 << 0)

// OTG_INTERFSEL register
#define PHYSEL   0
#define OTG_INTERFSEL_UTMI          (0 << PHYSEL)
#define OTG_INTERFSEL_12_PIN_ULPI   (1 << PHYSEL)
#define OTG_INTERFSEL_8_PIN_ULPI    (2 << PHYSEL)

// OTG_FORCESTDBY register
#define OTG_FORCESTDY_ENABLEFORCE   (1 << 0)

// AM3517_OTG_REGS.CONTROL
#define OTG_CONTROL_DIS_DEB			(1 << 31)
#define OTG_CONTROL_DIS_SRP			(1 << 30)
#define OTG_CONTROL_RNDIS			(1 <<  4)
#define OTG_CONTROL_UINT			(1 <<  3)
#define OTG_CONTROL_CLK_FACK		(1 <<  1)
#define OTG_CONTROL_RESET			(1 <<  0)

#endif
